---
products:
- product:
    product-name: Masajeador de espalda - Modificado por Fransito
- product:
    product-name: Colchoneta - Modificado por Adrian
- product:
    product-name: Muñequera - Modificado por Gabriel
- product:
    product-name: Zapatillas de Deporte - Modificado por Álvaro
